#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 07:22:20 PM +07  platform: Windows NT

import sys
import pandas as pd
import PilihProduk as pr
import Struk as s
from datetime import datetime

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def new(t_id, client):
    destroy_window()
    pr.add_product(t_id, client)

def new_transaction(t_id,client,total):
    target = 'Transaction.csv'
    tanggal = datetime.today().strftime('%Y-%m-%d-%H:%M:%S')
    df = pd.read_csv(target)
    df2 = pd.DataFrame([[t_id,tanggal,client,total]], 
                       columns=list(df.columns.values))
    df = pd.concat([df,df2])
    print(df)
    df.to_csv(target, index=False)
    destroy_window()
    s.finish(client)
    

if __name__ == '__main__':
    import Detail
    Detail.vp_start_gui()




