#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 07:22:20 PM +07  platform: Windows NT

import sys
import PilihProduk as pr

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def new(t_id, client):
    destroy_window()
    pr.add_product(t_id, client)

#def new_transaction(t_id,):
    
    

if __name__ == '__main__':
    import Detail
    Detail.vp_start_gui()




