#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 02:46:52 PM +07  platform: Windows NT

import sys
import Detail as d
import Login as l
import PilihPelanggan as pp
import Transaction as t
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def new():
    destroy_window()
    pp.vp_start_gui()

def logout():
    destroy_window()
    l.vp_start_gui()

if __name__ == '__main__':
    import ListTransaksi
    ListTransaksi.vp_start_gui()




