#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 09:44:18 AM +07  platform: Windows NT

import sys
import Account as ac
import Register
import ListTransaksi as lt
import Detail as d

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def login(username, password):
    result = ac.login(username, password)
    if result.tipe.values[0] == 'Karyawan':
        destroy_window()
        lt.show(result)
    else:
        destroy_window()
        d.show(result)

def register():
    destroy_window()
    Register.vp_start_gui()

if __name__ == '__main__':
    import Login
    Login.vp_start_gui()




