#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 09:45:18 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import BaseView
import Register

def start():
    vp_start_gui()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    BaseView.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    BaseView.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("363x276+342+202")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("LOGIN")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.405, rely=0.174, height=17, width=59)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Username''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.413, rely=0.435, height=17, width=56)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Password''')

        self.username = tk.Entry(top)
        self.username.place(relx=0.358, rely=0.254,height=20, relwidth=0.287)
        self.username.configure(background="white")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="TkFixedFont")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(insertbackground="black")
        self.username.configure(selectbackground="#c4c4c4")
        self.username.configure(selectforeground="black")

        self.password = tk.Entry(top)
        self.password.place(relx=0.386, rely=0.543,height=20, relwidth=0.231)
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="#c4c4c4")
        self.password.configure(selectforeground="black")
        self.password.config(show="*");

        self.login = tk.Button(top)
        self.login.place(relx=0.441, rely=0.725, height=24, width=41)
        self.login.configure(activebackground="#ececec")
        self.login.configure(activeforeground="#000000")
        self.login.configure(background="#d9d9d9")
        self.login.configure(command=lambda :BaseView.login(self.username.get(), self.password.get()))
        self.login.configure(disabledforeground="#a3a3a3")
        self.login.configure(foreground="#000000")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(pady="0")
        self.login.configure(text='''Login''')


        self.register = tk.Button(top)
        self.register.place(relx=0.826, rely=0.87, height=24, width=53)
        self.register.configure(activebackground="#ececec")
        self.register.configure(activeforeground="#000000")
        self.register.configure(background="#d9d9d9")
        self.register.configure(disabledforeground="#a3a3a3")
        self.register.configure(command=lambda :BaseView.redirect(Register))
        self.register.configure(foreground="#000000")
        self.register.configure(highlightbackground="#d9d9d9")
        self.register.configure(highlightcolor="black")
        self.register.configure(pady="0")
        self.register.configure(text='''Register''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)
        
if __name__ == '__main__':
    vp_start_gui()





