#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 08:53:34 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import BaseView
import AccountModel as am

def start(*args):
    global client, clientName, transaction
    transaction = args[0]
    client = am.getClient()
    clientName = [(i.username)for i in client]
    vp_start_gui()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    BaseView.set_Tk_var()
    top = Toplevel1 (root)
    BaseView.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    BaseView.set_Tk_var()
    top = Toplevel1 (w)
    BaseView.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("323x237+341+174")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title(" ")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.341, rely=0.211, height=15, width=103)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Pilih Pelanggan''')

        self.pelanggan = ttk.Combobox(top)
        self.pelanggan.place(relx=0.217, rely=0.338, relheight=0.105
                , relwidth=0.554)
        #self.pelanggan.configure(textvariable=BaseView.combobox)
        self.pelanggan['values'] = clientName
        self.pelanggan.configure(takefocus="")

        self.pick = tk.Button(top)
        self.pick.place(relx=0.372, rely=0.549, height=24, width=68)
        self.pick.configure(activebackground="#ececec")
        self.pick.configure(activeforeground="#000000")
        self.pick.configure(background="#d9d9d9")
        self.pick.configure(disabledforeground="#a3a3a3")
        self.pick.configure(foreground="#000000")
        self.pick.configure(highlightbackground="#d9d9d9")
        self.pick.configure(highlightcolor="black")
        self.pick.configure(pady="0")
        self.pick.configure(text='''Konfirmasi''')
        index = self.pelanggan.current()
        self.pick.configure(command=lambda :BaseView.viewCart(client[index], transaction))




