#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 28, 2020 02:26:27 PM +07  platform: Windows NT
#    May 28, 2020 02:28:23 PM +07  platform: Windows NT

import sys
import pandas as pd
import Detail as d

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def xxx(p1):
    print('PilihProduk_support.xxx')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def getProduk():
    return pd.read_csv('Produk.csv')

def add(t_id,client,produk,harga):
    target = 'Detail.csv'
    df = pd.read_csv(target)
    df2 = pd.DataFrame([[t_id,produk,harga]], 
                       columns=list(df.columns.values))
    df = pd.concat([df,df2])
    df.to_csv(target, index=False)
    destroy_window()
    d.add_product(t_id,client)

if __name__ == '__main__':
    import PilihProduk
    PilihProduk.vp_start_gui()



