#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 26, 2020 07:50:35 PM +07  platform: Windows NT

import sys
import Account as ac
from tkinter.messagebox import showinfo
import Login

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global type
    type = tk.StringVar()
    global username
    username = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None   

def register(tipe, username, email, password, c_password):
    if password == c_password:
        ac.register(tipe, username, email, password)
        showinfo("","Register Succeded !")
        login()
    else:
        showinfo("","Check Password !!!")

def login():
    destroy_window()
    Login.vp_start_gui()
        


if __name__ == '__main__':
    import Register
    Register.vp_start_gui()





