#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    May 27, 2020 08:18:41 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Login
import BaseView

def start():
    vp_start_gui()

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    BaseView.set_Tk_var()
    top = Toplevel1 (root)
    BaseView.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    BaseView.set_Tk_var()
    top = Toplevel1 (w)
    BaseView.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("434x346+390+147")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("REGISTER")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.415, rely=0.087, height=21, width=74)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Jenis Akun''')

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.415, rely=0.237, height=11, width=64)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Username''')

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.438, rely=0.384, height=21, width=44)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(cursor="fleur")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Email''')

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.415, rely=0.561, height=11, width=64)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Password''')

        self.Label1_4 = tk.Label(top)
        self.Label1_4.place(relx=0.369, rely=0.708, height=21, width=114)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Confirm Password''')

        self.type = ttk.Combobox(top)
        self.type.place(relx=0.323, rely=0.147, relheight=0.061, relwidth=0.329)
        self.type.configure(justify='center')
        self.type["values"] = ["Pelanggan", "Karyawan"]
        self.type.configure(textvariable=BaseView.type)
        self.type.configure(takefocus="")

        self.username = tk.Entry(top)
        self.username.place(relx=0.323, rely=0.295,height=20, relwidth=0.332)
        self.username.configure(background="white")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="TkFixedFont")
        self.username.configure(foreground="#000000")
        self.username.configure(insertbackground="black")
        #self.username.configure(textvariable=BaseView.username)
        self.username.configure(text='''Username''')

        self.email = tk.Entry(top)
        self.email.place(relx=0.332, rely=0.457,height=20, relwidth=0.332)
        self.email.configure(background="white")
        self.email.configure(disabledforeground="#a3a3a3")
        self.email.configure(font="TkFixedFont")
        self.email.configure(foreground="#000000")
        self.email.configure(highlightbackground="#d9d9d9")
        self.email.configure(highlightcolor="black")
        self.email.configure(insertbackground="black")
        self.email.configure(selectbackground="#c4c4c4")
        self.email.configure(selectforeground="black")

        self.password = tk.Entry(top)
        self.password.place(relx=0.323, rely=0.618,height=20, relwidth=0.332)
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="#c4c4c4")
        self.password.configure(selectforeground="black")
        self.password.config(show="*");

        self.c_password = tk.Entry(top)
        self.c_password.place(relx=0.323, rely=0.78,height=20, relwidth=0.332)
        self.c_password.configure(background="white")
        self.c_password.configure(disabledforeground="#a3a3a3")
        self.c_password.configure(font="TkFixedFont")
        self.c_password.configure(foreground="#000000")
        self.c_password.configure(highlightbackground="#d9d9d9")
        self.c_password.configure(highlightcolor="black")
        self.c_password.configure(insertbackground="black")
        self.c_password.configure(selectbackground="#c4c4c4")
        self.c_password.configure(selectforeground="black")
        self.c_password.config(show="*");

        self.register = tk.Button(top)
        self.register.place(relx=0.438, rely=0.867, height=24, width=53)
        self.register.configure(activebackground="#ececec")
        self.register.configure(activeforeground="#000000")
        self.register.configure(background="#d9d9d9")
        self.register.configure(cursor="fleur")
        self.register.configure(command=lambda :BaseView.register(
            self.type.get(), 
            self.username.get(), 
            self.email.get(), 
            self.password.get(),
            self.c_password.get()))
        self.register.configure(disabledforeground="#a3a3a3")
        self.register.configure(foreground="#000000")
        self.register.configure(highlightbackground="#d9d9d9")
        self.register.configure(highlightcolor="black")
        self.register.configure(pady="0")
        self.register.configure(text='''Register''')

        self.login = tk.Button(top)
        self.login.place(relx=0.853, rely=0.029, height=24, width=41)
        self.login.configure(activebackground="#ececec")
        self.login.configure(activeforeground="#000000")
        self.login.configure(background="#d9d9d9")
        self.login.configure(command=lambda :BaseView.redirect(Login))
        self.login.configure(disabledforeground="#a3a3a3")
        self.login.configure(foreground="#000000")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(pady="0")
        self.login.configure(text='''Login''')







